logging:
  filename: cpdbench-log.txt
  log-level: DEBUG
  log-level-console: WARNING
multiprocessing: True

result:
  filename: cpdbench-result.json


user:
  bound: 30
  element: [5919, 39319, 313]
  dataset-executions:

  algorithm-executions:

  metric-executions:
    - window_size: 50
    - window_size: 21